openapi: 3.0.1
info:
  contact:
    email: cmdi@clarin.eu
    name: CLARIN ERIC
    url: https://www.clarin.eu
  description: Components and profiles registry for the Component Metadata Infrastructure
  title: Component Registry API
  version: "1.0"
servers:
- url: /
paths:
  /rest/registry/items/{componentId}:
    get:
      operationId: getItem
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseDescription'
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseDescription'
          description: default response
      x-accepts:
      - application/json
      - application/xml
  /rest/registry/items/{componentId}/spec:
    get:
      operationId: getItemSpec
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentSpec'
            application/xml:
              schema:
                $ref: '#/components/schemas/ComponentSpec'
          description: default response
      x-accepts:
      - application/json
      - application/xml
  /rest/registry/items:
    get:
      operationId: getItems
      parameters:
      - explode: true
        in: query
        name: sortBy
        required: false
        schema:
          default: name
          type: string
        style: form
      - explode: true
        in: query
        name: sortDirection
        required: false
        schema:
          default: ASC
          enum:
          - ASC
          - DESC
          type: string
        style: form
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseDescription'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/BaseDescription'
                type: array
          description: default response
      x-accepts:
      - application/json
      - application/xml
  /rest/application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - explode: false
        in: path
        name: path
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
          description: default response
      x-accepts:
      - application/xml
  /rest/application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
          description: default response
      x-accepts:
      - application/vnd.sun.wadl+xml
      - application/xml
components:
  schemas:
    BaseDescription:
      example:
        successor: successor
        creatorName: creatorName
        description: description
        derivedfrom: derivedfrom
        dbUserId: 6
        userId: userId
        content: content
        recommended: true
        groupName: groupName
        deleted: true
        public: true
        commentsCount: 1
        dbId: 0
        domainName: domainName
        name: name
        registrationDate: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        href: href
        id: id
        showInEditor: true
        status: development
      properties:
        dbId:
          format: int64
          type: integer
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        dbUserId:
          format: int64
          type: integer
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        content:
          type: string
        deleted:
          type: boolean
        recommended:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        showInEditor:
          type: boolean
        isPublic:
          type: boolean
      type: object
      xml:
        name: description
    Attribute:
      example:
        conceptLink: conceptLink
        valueScheme: BOOLEAN
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        name: name
        attributeValueScheme:
          vocabulary:
            valueLanguage: valueLanguage
            enumeration:
              item:
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              appinfo: appinfo
            uri: uri
            valueProperty: valueProperty
          pattern: pattern
        otherAttributes:
          key: otherAttributes
        required: true
        autoValue:
        - autoValue
        - autoValue
      properties:
        documentation:
          items:
            $ref: '#/components/schemas/DocumentationType'
          type: array
          xml:
            name: Documentation
        attributeValueScheme:
          $ref: '#/components/schemas/ValueSchemeType'
        autoValue:
          items:
            type: string
            xml:
              name: AutoValue
          type: array
          xml:
            name: AutoValue
        name:
          type: string
          xml:
            attribute: true
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        valueScheme:
          enum:
          - BOOLEAN
          - DECIMAL
          - FLOAT
          - INT
          - STRING
          - ANY_URI
          - DATE
          - G_DAY
          - G_MONTH
          - G_YEAR
          - TIME
          - DATE_TIME
          type: string
          xml:
            attribute: true
            name: ValueScheme
        required:
          type: boolean
          xml:
            attribute: true
            name: Required
        otherAttributes:
          additionalProperties:
            type: string
          type: object
      type: object
    AttributeListType:
      example:
        attribute:
        - conceptLink: conceptLink
          valueScheme: BOOLEAN
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          name: name
          attributeValueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          otherAttributes:
            key: otherAttributes
          required: true
          autoValue:
          - autoValue
          - autoValue
        - conceptLink: conceptLink
          valueScheme: BOOLEAN
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          name: name
          attributeValueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          otherAttributes:
            key: otherAttributes
          required: true
          autoValue:
          - autoValue
          - autoValue
      properties:
        attribute:
          items:
            $ref: '#/components/schemas/Attribute'
          type: array
          xml:
            name: Attribute
      required:
      - attribute
      type: object
    ComponentSpec:
      example:
        isProfile: true
        cmdoriginalVersion: cmdoriginalVersion
        component:
          component:
          - null
          - null
          conceptLink: conceptLink
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          componentRef: componentRef
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          element:
          - conceptLink: conceptLink
            valueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            attributeList:
              attribute:
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
            name: name
            cardinalityMin:
            - cardinalityMin
            - cardinalityMin
            cardinalityMax:
            - cardinalityMax
            - cardinalityMax
            otherAttributes:
              key: otherAttributes
            multilingual: true
            ValueSchemeType: BOOLEAN
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            attributeList:
              attribute:
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
            name: name
            cardinalityMin:
            - cardinalityMin
            - cardinalityMin
            cardinalityMax:
            - cardinalityMax
            - cardinalityMax
            otherAttributes:
              key: otherAttributes
            multilingual: true
            ValueSchemeType: BOOLEAN
            autoValue:
            - autoValue
            - autoValue
          base: base
        header:
          successor: successor
          name: name
          derivedFrom: derivedFrom
          description: description
          id: id
          statusComment: statusComment
          status: status
        cmdversion: cmdversion
      properties:
        header:
          $ref: '#/components/schemas/Header'
        component:
          $ref: '#/components/schemas/ComponentType'
        isProfile:
          type: boolean
          xml:
            attribute: true
        cmdversion:
          type: string
        cmdoriginalVersion:
          type: string
      required:
      - component
      - header
      type: object
      xml:
        name: ComponentSpec
    ComponentType:
      example:
        component:
        - null
        - null
        conceptLink: conceptLink
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        attributeList:
          attribute:
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
        name: name
        componentRef: componentRef
        cardinalityMin:
        - cardinalityMin
        - cardinalityMin
        cardinalityMax:
        - cardinalityMax
        - cardinalityMax
        otherAttributes:
          key: otherAttributes
        element:
        - conceptLink: conceptLink
          valueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          multilingual: true
          ValueSchemeType: BOOLEAN
          autoValue:
          - autoValue
          - autoValue
        - conceptLink: conceptLink
          valueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          multilingual: true
          ValueSchemeType: BOOLEAN
          autoValue:
          - autoValue
          - autoValue
        base: base
      properties:
        documentation:
          items:
            $ref: '#/components/schemas/DocumentationType'
          type: array
          xml:
            name: Documentation
        attributeList:
          $ref: '#/components/schemas/AttributeListType'
        element:
          items:
            $ref: '#/components/schemas/ElementType'
          type: array
          xml:
            name: Element
        component:
          items:
            $ref: '#/components/schemas/ComponentType'
          type: array
          xml:
            name: Component
        name:
          type: string
          xml:
            attribute: true
        componentRef:
          type: string
          xml:
            attribute: true
            name: ComponentRef
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        cardinalityMin:
          items:
            type: string
          type: array
        cardinalityMax:
          items:
            type: string
          type: array
        base:
          type: string
          xml:
            attribute: true
            namespace: http://www.w3.org/XML/1998/namespace
        otherAttributes:
          additionalProperties:
            type: string
          type: object
      type: object
    DocumentationType:
      example:
        lang: lang
        value: value
      properties:
        value:
          type: string
        lang:
          type: string
          xml:
            attribute: true
            namespace: http://www.w3.org/XML/1998/namespace
      type: object
    ElementType:
      example:
        conceptLink: conceptLink
        valueScheme:
          vocabulary:
            valueLanguage: valueLanguage
            enumeration:
              item:
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              appinfo: appinfo
            uri: uri
            valueProperty: valueProperty
          pattern: pattern
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        attributeList:
          attribute:
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
        name: name
        cardinalityMin:
        - cardinalityMin
        - cardinalityMin
        cardinalityMax:
        - cardinalityMax
        - cardinalityMax
        otherAttributes:
          key: otherAttributes
        multilingual: true
        ValueSchemeType: BOOLEAN
        autoValue:
        - autoValue
        - autoValue
      properties:
        documentation:
          items:
            $ref: '#/components/schemas/DocumentationType'
          type: array
          xml:
            name: Documentation
        attributeList:
          $ref: '#/components/schemas/AttributeListType'
        valueScheme:
          $ref: '#/components/schemas/ValueSchemeType'
        autoValue:
          items:
            type: string
            xml:
              name: AutoValue
          type: array
          xml:
            name: AutoValue
        name:
          type: string
          xml:
            attribute: true
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        cardinalityMin:
          items:
            type: string
          type: array
        cardinalityMax:
          items:
            type: string
          type: array
        multilingual:
          type: boolean
          xml:
            attribute: true
            name: Multilingual
        otherAttributes:
          additionalProperties:
            type: string
          type: object
        ValueSchemeType:
          enum:
          - BOOLEAN
          - DECIMAL
          - FLOAT
          - INT
          - STRING
          - ANY_URI
          - DATE
          - G_DAY
          - G_MONTH
          - G_YEAR
          - TIME
          - DATE_TIME
          type: string
          xml:
            attribute: true
            name: ValueScheme
      type: object
    EnumerationType:
      example:
        item:
        - conceptLink: conceptLink
          appInfo: appInfo
          value: value
          otherAttributes:
            key: otherAttributes
        - conceptLink: conceptLink
          appInfo: appInfo
          value: value
          otherAttributes:
            key: otherAttributes
        appinfo: appinfo
      properties:
        appinfo:
          type: string
        item:
          items:
            $ref: '#/components/schemas/ItemType'
          type: array
      required:
      - item
      type: object
    Header:
      example:
        successor: successor
        name: name
        derivedFrom: derivedFrom
        description: description
        id: id
        statusComment: statusComment
        status: status
      properties:
        id:
          type: string
          xml:
            name: ID
        name:
          type: string
          xml:
            name: Name
        description:
          type: string
          xml:
            name: Description
        status:
          type: string
          xml:
            name: Status
        statusComment:
          type: string
          xml:
            name: StatusComment
        successor:
          type: string
          xml:
            name: Successor
        derivedFrom:
          type: string
          xml:
            name: DerivedFrom
      required:
      - id
      - name
      - status
      type: object
    ItemType:
      example:
        conceptLink: conceptLink
        appInfo: appInfo
        value: value
        otherAttributes:
          key: otherAttributes
      properties:
        value:
          type: string
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        appInfo:
          type: string
          xml:
            attribute: true
            name: AppInfo
        otherAttributes:
          additionalProperties:
            type: string
          type: object
      type: object
    ValueSchemeType:
      example:
        vocabulary:
          valueLanguage: valueLanguage
          enumeration:
            item:
            - conceptLink: conceptLink
              appInfo: appInfo
              value: value
              otherAttributes:
                key: otherAttributes
            - conceptLink: conceptLink
              appInfo: appInfo
              value: value
              otherAttributes:
                key: otherAttributes
            appinfo: appinfo
          uri: uri
          valueProperty: valueProperty
        pattern: pattern
      properties:
        pattern:
          type: string
        vocabulary:
          $ref: '#/components/schemas/VocabularyType'
      type: object
    VocabularyType:
      example:
        valueLanguage: valueLanguage
        enumeration:
          item:
          - conceptLink: conceptLink
            appInfo: appInfo
            value: value
            otherAttributes:
              key: otherAttributes
          - conceptLink: conceptLink
            appInfo: appInfo
            value: value
            otherAttributes:
              key: otherAttributes
          appinfo: appinfo
        uri: uri
        valueProperty: valueProperty
      properties:
        enumeration:
          $ref: '#/components/schemas/EnumerationType'
        uri:
          type: string
          xml:
            attribute: true
            name: URI
        valueProperty:
          type: string
          xml:
            attribute: true
            name: ValueProperty
        valueLanguage:
          type: string
          xml:
            attribute: true
            name: ValueLanguage
      type: object

